language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy ./reverseproxy
  - docker tag udagram-reverseproxy ahmedelsherbini/udagram-reverseproxy:latest
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed ahmedelsherbini/udagram-api-feed:latest
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user ahmedelsherbini/udagram-api-user:latest
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend ahmedelsherbini/udagram-frontend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ahmedelsherbini/reverseproxy
  - docker push ahmedelsherbini/udagram-api-feed
  - docker push ahmedelsherbini/udagram-api-user
  - docker push ahmedelsherbini/udagram-frontend